Add support for NPM dep, and compatibility for "rm" (#7521)
* Use grep and add npm support

* MacOS rm order matters

* Validated all build

* v0.0.0

* Move to Node version check

* Modified docs to show install step

* Add golang output

* Proper minor version check

* Fixed yarn install steps

* Clean out old files
Add yarn msg for install

* Update docs/developer/getting-started.md

Co-authored-by: Samir Romdhani <romdhanisamir94@gmail.com>
Signed-off-by: Marcin Maciaszczyk <marcin9yk@icloud.com>

* Lint markdown

* Update tools makefile

* Update getting stared docs

* Update node version in check

---------

Signed-off-by: Marcin Maciaszczyk <marcin9yk@icloud.com>
Co-authored-by: Marcin Maciaszczyk <marcin9yk@icloud.com>
Co-authored-by: Samir Romdhani <romdhanisamir94@gmail.com>

diff --git a/modules/common/tools/Makefile b/modules/common/tools/Makefile
--- a/modules/common/tools/Makefile
+++ b/modules/common/tools/Makefile
@@ -1,8 +1,10 @@
-LICENSE_EYE_BINARY := $(shell which license-eye)
-AIR_BINARY := $(shell which air)
-GOLANGCI_LINT_BINARY := $(shell which golangci-lint)
-CLIENT_GEN_BINARY := $(shell which client-gen)
-GENGO_DIR := "${GOPATH}/src/k8s.io/gengo"
+NODE_BINARY := $(shell which node)
+NODE_MAJOR_VERSION = $(shell node --version | cut -d'.' -f1 | cut -d'v' -f2 )
+NODE_MINOR_VERSION = $(shell node --version | cut -d'.' -f2)
+MIN_NODE_MAJOR_VERSION = 18
+MIN_NODE_MINOR_VERSION = 14
+
+YARN_BINARY := $(shell which yarn)
 
 GO_BINARY := $(shell which go)
 GO_MAJOR_VERSION = $(shell go version | cut -c 14- | cut -d' ' -f1 | cut -d'.' -f1)
@@ -10,10 +12,41 @@ GO_MINOR_VERSION = $(shell go version | cut -c 14- | cut -d' ' -f1 | cut -d'.' -
 MIN_GO_MAJOR_VERSION = 1
 MIN_GO_MINOR_VERSION = 19
 
-# TODO: It should check not only if binaries are installed but also their versions
+GENGO_DIR := "${GOPATH}/src/k8s.io/gengo"
+LICENSE_EYE_BINARY := $(shell which license-eye)
+AIR_BINARY := $(shell which air)
+GOLANGCI_LINT_BINARY := $(shell which golangci-lint)
+CLIENT_GEN_BINARY := $(shell which client-gen)
 
 .PHONY: install
-install: ensure-go install-license-eye install-air install-golangci-lint install-client-gen ensure-gengo
+install: ensure-node ensure-yarn ensure-go ensure-gengo install-license-eye install-air install-golangci-lint install-client-gen
+
+.PHONY: ensure-node
+ensure-node:
+ifndef NODE_BINARY
+	$(error "Cannot find node binary")
+endif
+	@if [ $(NODE_MAJOR_VERSION) -gt $(MIN_NODE_MAJOR_VERSION) ]; then \
+		echo "[tools] node version requirements met"; \
+		exit 0 ;\
+	elif [ $(NODE_MAJOR_VERSION) -lt $(MIN_NODE_MAJOR_VERSION) ]; then \
+		echo "[tools] node version older than required v$(MIN_NODE_MAJOR_VERSION).$(MIN_NODE_MINOR_VERSION).0+"; \
+		exit 1; \
+	elif [ $(NODE_MINOR_VERSION) -lt $(NODE_MINOR_VERSION) ] ; then \
+		echo "[tools] node version older than required v$(MIN_NODE_MAJOR_VERSION).$(MIN_NODE_MINOR_VERSION).0+"; \
+		exit 1; \
+	else \
+		echo "[tools] node version requirements met"; \
+	fi
+
+.PHONY: ensure-yarn
+ensure-yarn:
+ifndef YARN_BINARY
+	@echo "[tools] yarn required to build front-end"
+	@echo "[tools] see how to install yarn at: https://yarnpkg.com/getting-started/install"
+else
+	@echo "[tools] yarn already exists"
+endif
 
 .PHONY: ensure-go
 ensure-go:
@@ -22,11 +55,21 @@ ifndef GO_BINARY
 endif
 	@if [ $(GO_MAJOR_VERSION) -gt $(MIN_GO_MAJOR_VERSION) ]; then \
 		exit 0 ;\
-  elif [ $(GO_MAJOR_VERSION) -lt $(MIN_GO_MAJOR_VERSION) ]; then \
+	elif [ $(GO_MAJOR_VERSION) -lt $(MIN_GO_MAJOR_VERSION) ]; then \
+		echo "[tools] go version older than required v$(MIN_GO_MAJOR_VERSION).$(MIN_GO_MINOR_VERSION).0+"; \
 		exit 1; \
-  elif [ $(GO_MINOR_VERSION) -lt $(MIN_GO_MINOR_VERSION) ] ; then \
+	elif [ $(GO_MINOR_VERSION) -lt $(MIN_GO_MINOR_VERSION) ] ; then \
+		echo "[tools] go version older than required v$(MIN_GO_MAJOR_VERSION).$(MIN_GO_MINOR_VERSION).0+"; \
 		exit 1; \
-  fi
+	else \
+		echo "[tools] golang version requirements met"; \
+	fi
+
+.PHONY: ensure-gengo
+ensure-gengo:
+	@echo "[tools] ensure k8s.io/gengo..."
+	@rm -fr ${GENGO_DIR}
+	@git clone https://github.com/kubernetes/gengo ${GENGO_DIR}
 
 .PHONY: install-license-eye
 install-license-eye:
@@ -63,9 +106,3 @@ ifndef CLIENT_GEN_BINARY
 else
 	@echo "[tools] client-gen already exists"
 endif
-
-.PHONY: ensure-gengo
-ensure-gengo:
-	@echo "[tools] ensure k8s.io/gengo..."
-	@rm -fr ${GENGO_DIR}
-	@git clone https://github.com/kubernetes/gengo ${GENGO_DIR}
